import os

BLOCKCHAIN_NOBROADCAST = False

BITSHARES_GATEWAY_ACCOUNT = os.environ.get('BITSHARES_GATEWAY_ACCOUNT')
BITSHARES_GATEWAY_WIF = os.environ.get('BITSHARES_GATEWAY_WIF')
BITSHARES_GATEWAY_WIF_MEMO = os.environ.get('BITSHARES_GATEWAY_WIF_MEMO')
BITSHARES_NODE_URL = os.environ.get('BITSHARES_NODE_URL')

TRANSNET_GATEWAY_ACCOUNT = os.environ.get('TRANSNET_GATEWAY_ACCOUNT')
TRANSNET_GATEWAY_WIF = os.environ.get('TRANSNET_GATEWAY_WIF')
TRANSNET_GATEWAY_WIF_MEMO = os.environ.get('TRANSNET_GATEWAY_WIF_MEMO')
TRANSNET_NODE_URL = os.environ.get('TRANSNET_NODE_URL')