# Generated by Django 2.0.2 on 2018-03-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitsharesTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(max_length=512, verbose_name='ID транзакции')),
                ('trx_in_block', models.PositiveIntegerField(verbose_name='Номер транзакции в блоке')),
                ('op_in_trx', models.PositiveIntegerField(verbose_name='Номер операции в транзакции')),
                ('asset', models.CharField(max_length=128, verbose_name='Токен')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Количество средст')),
                ('account_external', models.CharField(max_length=128, verbose_name='Внешний аккаунт')),
                ('account_internal', models.CharField(max_length=128, verbose_name='Внутренний аккаунт')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('error', models.BooleanField(default=False, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'транзакция в BitShares',
                'verbose_name_plural': 'транзакции в BitShares',
            },
        ),
        migrations.CreateModel(
            name='TransnetTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(max_length=512, verbose_name='ID транзакции')),
                ('trx_in_block', models.PositiveIntegerField(verbose_name='Номер транзакции в блоке')),
                ('op_in_trx', models.PositiveIntegerField(verbose_name='Номер операции в транзакции')),
                ('asset', models.CharField(max_length=128, verbose_name='Токен')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Количество средст')),
                ('account_external', models.CharField(max_length=128, verbose_name='Внешний аккаунт')),
                ('account_internal', models.CharField(max_length=128, verbose_name='Внутренний аккаунт')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('error', models.BooleanField(default=False, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'транзакция в Transnet',
                'verbose_name_plural': 'транзакции в Transnet',
            },
        ),
    ]
