# Generated by Django 2.0.2 on 2018-03-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20180324_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitsharestransaction',
            name='amount',
            field=models.FloatField(verbose_name='Количество средст'),
        ),
        migrations.AlterField(
            model_name='transnettransaction',
            name='amount',
            field=models.FloatField(verbose_name='Количество средст'),
        ),
    ]
