# Generated by Django 2.0.2 on 2018-04-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_auto_20180403_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransnetTransaction',
            new_name='BitsharesTransnetTransaction',
        ),
        migrations.RenameModel(
            old_name='BitsharesTransaction',
            new_name='TransnetBitsharesTransaction',
        ),
        migrations.AlterModelOptions(
            name='bitsharestransnettransaction',
            options={'ordering': ('-trx_id',), 'verbose_name': 'Bitshares в Transnet', 'verbose_name_plural': 'Bitshares в Transnet'},
        ),
        migrations.AlterModelOptions(
            name='transnetbitsharestransaction',
            options={'ordering': ('-trx_id',), 'verbose_name': 'Transnet в Bitshares', 'verbose_name_plural': 'Transnet в Bitshares'},
        ),
    ]
