# Generated by Django 2.0.2 on 2018-04-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_auto_20180405_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitsharestransnettransaction',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='bitsharestransnettransaction',
            name='error',
        ),
        migrations.RemoveField(
            model_name='transnetbitsharestransaction',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='transnetbitsharestransaction',
            name='error',
        ),
        migrations.AddField(
            model_name='bitsharestransnettransaction',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('complete', 'Complete'), ('error', 'Error')], default='idle', max_length=10, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='transnetbitsharestransaction',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('complete', 'Complete'), ('error', 'Error')], default='idle', max_length=10, verbose_name='State'),
        ),
    ]
