# Generated by Django 2.0.2 on 2018-04-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitshares_transnet_gateway_address', models.CharField(max_length=255, verbose_name='адрес')),
                ('bitshares_transnet_active_wif', models.CharField(max_length=255, verbose_name='активный ключ')),
                ('bitshares_transnet_memo_wif', models.CharField(max_length=255, verbose_name='memo ключ')),
                ('bitshares_transnet_node_url', models.URLField(verbose_name='адрес ноды для подключения')),
                ('transnet_bitshares_gateway_address', models.CharField(max_length=255, verbose_name='адрес')),
                ('transnet_bitshares_active_wif', models.CharField(max_length=255, verbose_name='активный ключ')),
                ('transnet_bitshares_memo_wif', models.CharField(max_length=255, verbose_name='memo ключ')),
                ('transnet_bitshares_node_url', models.URLField(verbose_name='адрес ноды для подключения')),
            ],
        ),
    ]
