# Generated by Django 2.0.2 on 2018-04-03 23:59

from django.db import migrations
from django.db.migrations import RunPython


def create_instance(apps, schema_editor):
    SettingsModel = apps.get_model('site_settings', 'SettingsModel')
    SettingsModel.objects.get_or_create(pk=1)


class Migration(migrations.Migration):
    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        RunPython(create_instance)
    ]
