# Generated by Django 2.0.2 on 2018-04-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20180403_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='bitshares_transnet_active_wif',
            field=models.CharField(max_length=255, verbose_name='Active key (WIF)'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='bitshares_transnet_gateway_address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='bitshares_transnet_memo_wif',
            field=models.CharField(max_length=255, verbose_name='Memo key (WIF)'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='bitshares_transnet_node_url',
            field=models.URLField(verbose_name='URL of node'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='transnet_bitshares_active_wif',
            field=models.CharField(max_length=255, verbose_name='Active key (WIF)'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='transnet_bitshares_gateway_address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='transnet_bitshares_memo_wif',
            field=models.CharField(max_length=255, verbose_name='Memo key (WIF)'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='transnet_bitshares_node_url',
            field=models.URLField(verbose_name='URL of node'),
        ),
    ]
