# Generated by Django 2.0.2 on 2018-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20180405_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsmodel',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='bitshares_transnet_node_url',
            field=models.CharField(max_length=255, verbose_name='URL of node'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='transnet_bitshares_node_url',
            field=models.CharField(max_length=255, verbose_name='URL of node'),
        ),
    ]
