# Generated by Django 2.0.2 on 2018-04-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20180405_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='bitshares_transnet_gateway_address',
            field=models.CharField(help_text='Address of the account that will be used as gateway in BitShares', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='bitshares_transnet_node_url',
            field=models.CharField(help_text='URL of the node for interacting with BitShares', max_length=255, verbose_name='URL of node'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='transnet_bitshares_gateway_address',
            field=models.CharField(help_text='Address of the account that will be used as gateway in Transnet', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='transnet_bitshares_node_url',
            field=models.CharField(help_text='URL of the node for interacting with Transnet', max_length=255, verbose_name='URL of node'),
        ),
    ]
